name: JUNIT-ANT-1

on:
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Run Ant Build
          working-directory:./java-junit-template-project-master
        run: ant clean test

      - name: Generate Test Summary Report
          working-directory:./java-junit-template-project-master
        run: ant junitreport

      - name: Upload JUnit Report and Summary
        uses: actions/upload-artifact@v2
        with:
          name: junit-report
          path: |
           ./java-junit-template-project-master/build/test-results
           ./java-junit-template-project-master/build/junit
