name: JUNIT-ANT-1

on:
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Run Ant Build
        working-directory: java-junit-template-project-master
        run: ant clean test
        
      - name: Report JUnit Tests with Dorny (if tests are successful)
        uses: dorny/test-reporter@v1
        if: success()  # This step only runs if the previous step (test) succeeds
        with:
          name: "JUnit Tests"
          path: "**/test-results/*.xml"  # Assuming your test results are in test-results/*.xml
          reporter: "junit"
          fail-on-error: true
