name: test_DATA_01

on:
  workflow_dispatch:

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

  # Pause placeholder job
  pause_workflow:
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
      - name: Pause Workflow
        run: echo "::set-output name=pause_workflow::true"
        id: pause_workflow

  #---------------- Docker
  DOCKERHUB:
    needs: [pause_workflow]
    runs-on: ubuntu-latest
    if: ${{ needs.pause_workflow.outputs.pause_workflow != 'true' }}
    environment:
      name: DEVELOPMENT
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dockerimagebuild:main
