name: test_DATA_01

on:
  workflow_dispatch:
    inputs:
      pause_workflow:
        description: 'Pause the workflow'
        required: false
        default: 'false'

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

  check_pause:
    runs-on: ubuntu-latest
    if: github.event.inputs.pause_workflow == 'true'
    steps:
      - name: Pause Workflow
        run: echo "Workflow paused"

  approval:
    needs: [build, check_pause]
    runs-on: ubuntu-latest
    if: github.event.inputs.pause_workflow != 'true'
    steps:
      - name: Request Approval
        id: approval
        uses: "marvinpinto/action-automatic-approvals@v1"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          approvers: "username1,username2"  # Add the usernames of the approvers
          comment: "Approve to proceed with DockerHub job"
          wait_for: "comment"

  DOCKERHUB:
    needs: [approval]
    runs-on: ubuntu-latest
    if: github.event.inputs.pause_workflow != 'true'
    environment:
      name: DEVELOPMENT
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dockerimagebuild:main
