name: test_DATA_01

on:
  workflow_dispatch:
  # You can add other events if needed

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

  # Manual approval job
  manual-approval:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Pause until approval
        id: pause
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, run_id } = github.context;
            const resp = await octokit.request('POST /repos/{owner}/{repo}/actions/runs/{run_id}/pending-approval');
            console.log(resp);

  DOCKERHUB:
    needs: [manual-approval]
    runs-on: ubuntu-latest
    environment:
      name: DEVELOPMENT
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dockerimagebuild:main
